/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BloodGlucoseCheckInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getMyGlucoseValue"
      | "getMyResult"
      | "getMySubmissionTime"
      | "hasSubmitted"
      | "hasUserSubmitted"
      | "submissionTimestamp"
      | "submitGlucoseValue"
      | "userGlucoseValues"
      | "userResults"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "GlucoseSubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyGlucoseValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyResult",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMySubmissionTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserSubmitted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submissionTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitGlucoseValue",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userGlucoseValues",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userResults",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyGlucoseValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMySubmissionTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submissionTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitGlucoseValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userGlucoseValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userResults",
    data: BytesLike
  ): Result;
}

export namespace GlucoseSubmittedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BloodGlucoseCheck extends BaseContract {
  connect(runner?: ContractRunner | null): BloodGlucoseCheck;
  waitForDeployment(): Promise<this>;

  interface: BloodGlucoseCheckInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getMyGlucoseValue: TypedContractMethod<[], [string], "view">;

  getMyResult: TypedContractMethod<[], [string], "view">;

  getMySubmissionTime: TypedContractMethod<[], [bigint], "view">;

  hasSubmitted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  hasUserSubmitted: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  submissionTimestamp: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  submitGlucoseValue: TypedContractMethod<
    [encryptedGlucose: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  userGlucoseValues: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  userResults: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyGlucoseValue"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyResult"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMySubmissionTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasUserSubmitted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "submissionTimestamp"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitGlucoseValue"
  ): TypedContractMethod<
    [encryptedGlucose: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userGlucoseValues"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "userResults"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "GlucoseSubmitted"
  ): TypedContractEvent<
    GlucoseSubmittedEvent.InputTuple,
    GlucoseSubmittedEvent.OutputTuple,
    GlucoseSubmittedEvent.OutputObject
  >;

  filters: {
    "GlucoseSubmitted(address,uint256)": TypedContractEvent<
      GlucoseSubmittedEvent.InputTuple,
      GlucoseSubmittedEvent.OutputTuple,
      GlucoseSubmittedEvent.OutputObject
    >;
    GlucoseSubmitted: TypedContractEvent<
      GlucoseSubmittedEvent.InputTuple,
      GlucoseSubmittedEvent.OutputTuple,
      GlucoseSubmittedEvent.OutputObject
    >;
  };
}
